In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [17]:
abs=pd.read_excel("C:/Users/Venu/Desktop/HDS-Datasets_Exersice/Absenteeism_at_work.xls")

In [18]:
abs

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0    11                  26                 7                3        1   
1    36                   0                 7                3        1   
2     3                  23                 7                4        1   
3     7                   7                 7                5        1   
4    11                  23                 7                5        1   
5     3                  23                 7                6        1   
6    10                  22                 7                6        1   
7    20                  23                 7                6        1   
8    14                  19                 7                2        1   
9     1                  22                 7                2        1   
10   20                   1                 7                2        1   
11   20                   1                 7                3        1   
12   20                  11                 7                4        1   
13    3                  11                 7                4        1   
14    3                  23                 7                4        1   
15   24                  14                 7                6        1   
16    3                  23                 7                6        1   
17    3                  21                 7                2        1   
18    6                  11                 7                5        1   
19   33                  23                 8                4        1   
20   18                  10                 8                4        1   
21    3                  11                 8                2        1   
22   10                  13                 8                2        1   
23   20                  28                 8                6        1   
24   11                  18                 8                2        1   
25   10                  25                 8                2        1   
26   11                  23                 8                3        1   
27   30                  28                 8                4        1   
28   11                  18                 8                4        1   
29    3                  23                 8                6        1   
..   ..                 ...               ...              ...      ...   
710  23                  22                 6                5        3   
711  36                  19                 6                5        3   
712  12                  19                 6                6        3   
713  22                  27                 6                6        3   
714   2                   0                 6                2        3   
715  21                   0                 6                2        3   
716  36                  19                 6                5        3   
717  22                  13                 6                5        3   
718  15                  28                 6                5        3   
719  22                  13                 6                2        1   
720  34                  25                 6                2        1   
721  12                  22                 6                5        1   
722  34                   8                 6                6        1   
723  34                  10                 6                4        1   
724  12                  22                 6                4        1   
725   5                  26                 7                4        1   
726  12                  19                 7                6        1   
727   9                   6                 7                2        1   
728  34                  28                 7                2        1   
729   9                   6                 7                3        1   
730   6                  22                 7                3        1   
731  34                  23   

In [128]:
k=5
cent_change=0.0001
max_iter=300

In [129]:
colors=10*['g','r','c','b','k','y']

In [130]:
def fit(data,k,max_iter,tol):
    centroids={}
    for i in range(k):
        centroids[i]=data[i]
        
    for i in range(max_iter):
        classifications={}
        
        for i in range(k):
            classifications[i]=[]
        
        for featureset in data:
            distances=[np.linalg.norm(featureset-centroids[centroid]) for centroid in centroids]
            #print(distances)
            classification=distances.index(min(distances))
            #print(classification)
            classifications[classification].append(featureset)
            #print(classifiations)
        
        prev_centroids=dict(centroids)
    
        for classification in classifications:
            centroids[classification]=np.average(classifications[classification],axis=0)
        
        optimised=True
    
        for c in centroids:
            original_centroid=prev_centroids[c]
            current_centroid=centroids[c]
            if np.sum((current_centroid-original_centroid)/original_centroid*100.0)>tol:
                optimised=False
            
        if optimised:
            break
     
    return centroids, classifications

In [131]:
def predict(data,centroids):
    distances=[np.linalg.norm(data-centroids[centroid]) for centroid in centroids]
    classification=distances.index(min(distances))
    return classification

In [132]:
abs.keys()

Index(['ID', 'Seasons', 'Age', 'Work load Average/day ', 'Education', 'Son',
       'Pet', 'Weight', 'Height', 'Reason_for_absence', 'Month_of_absence',
       'Day_of_the_week', 'Transportation_expense',
       'Distance_from_Residence_to_Work', 'Service_time', 'Hit_target',
       'Disciplinary_failure', 'Social_drinker', 'Social_smoker',
       'Body_mass_index', 'Absenteeism_time_in_hours'],
      dtype='object')

In [133]:
features=pd.concat([abs.ID,abs.Reason_for_absence,abs.Month_of_absence,abs.Day_of_the_week,abs.Seasons,abs.Transportation_expense,abs.Distance_from_Residence_to_Work,abs.Service_time,abs.Age,abs.Hit_target,abs.Education,abs.Son,abs.Disciplinary_failure,abs.Social_drinker,abs.Social_smoker,abs.Pet,abs.Weight,abs.Height,abs.Body_mass_index],axis=1)

In [134]:
features

ID  Reason_for_absence  Month_of_absence  Day_of_the_week  \
0    0.285714            0.928571          0.583333             0.25   
1    1.000000            0.000000          0.583333             0.25   
2    0.057143            0.821429          0.583333             0.50   
3    0.171429            0.250000          0.583333             0.75   
4    0.285714            0.821429          0.583333             0.75   
5    0.057143            0.821429          0.583333             1.00   
6    0.257143            0.785714          0.583333             1.00   
7    0.542857            0.821429          0.583333             1.00   
8    0.371429            0.678571          0.583333             0.00   
9    0.000000            0.785714          0.583333             0.00   
10   0.542857            0.035714          0.583333             0.00   
11   0.542857            0.035714          0.583333             0.25   
12   0.542857            0.392857          0.583333             0.50   
13   0.057143            0.392857          0.583333             0.50   
14   0.057143            0.821429          0.583333             0.50   
15   0.657143            0.500000          0.583333             1.00   
16   0.057143            0.821429          0.583333             1.00   
17   0.057143            0.750000          0.583333             0.00   
18   0.142857            0.392857          0.583333             0.75   
19   0.914286            0.821429          0.666667             0.50   
20   0.485714            0.357143          0.666667             0.50   
21   0.057143            0.392857          0.666667             0.00   
22   0.257143            0.464286          0.666667             0.00   
23   0.542857            1.000000          0.666667             1.00   
24   0.285714            0.642857          0.666667             0.00   
25   0.257143            0.892857          0.666667             0.00   
26   0.285714            0.821429          0.666667             0.25   
27   0.828571            1.000000          0.666667             0.50   
28   0.285714            0.642857          0.666667             0.50   
29   0.057143            0.821429          0.666667             1.00   
..        ...                 ...               ...              ...   
710  0.628571            0.785714          0.500000             0.75   
711  1.000000            0.678571          0.500000             0.75   
712  0.314286            0.678571          0.500000             1.00   
713  0.600000            0.964286          0.500000             1.00   
714  0.028571            0.000000          0.500000             0.00   
715  0.571429            0.000000          0.500000             0.00   
716  1.000000            0.678571          0.500000             0.75   
717  0.600000            0.464286          0.500000             0.75   
718  0.400000            1.000000          0.500000             0.75   
719  0.600000            0.464286          0.500000             0.00   
720  0.942857            0.892857          0.500000             0.00   
721  0.314286            0.785714          0.500000             0.75   
722  0.942857            0.285714          0.500000             1.00   
723  0.942857            0.357143          0.500000             0.50   
724  0.314286            0.785714          0.500000             0.50   
725  0.114286            0.928571          0.583333             0.50   
726  0.314286            0.678571          0.583333             1.00   
727  0.228571            0.214286          0.583333             0.00   
728  0.942857            1.000000          0.583333             0.00   
729  0.228571            0.214286          0.583333             0.25   
730  0.142857            0.785714          0.583333             0.25   
731  0.942857            0.821429          0.583333             0.50   
732  0.257143            0.785714          0.583333             0.50   
733  0.771429            0.785714          0.583333

In [135]:
target=pd.concat([abs.Absenteeism_time_in_hours],axis=1)

In [136]:
abs=(abs-abs.min())/(abs.max()-abs.min())

In [137]:
xtrain,xtest =train_test_split(abs,test_size=0.3)

In [138]:
corelation=abs.corr('pearson')
corelation

ID   Seasons       Age  \
ID                               1.000000  0.098495  0.040899   
Seasons                          0.098495  1.000000 -0.012089   
Age                              0.040899 -0.012089  1.000000   
Work load Average/day            0.092457  0.150439 -0.039425   
Education                       -0.036254 -0.002951 -0.221882   
Son                              0.002767  0.046950  0.056984   
Pet                             -0.041418  0.012356 -0.231226   
Weight                          -0.254222 -0.026278  0.418730   
Height                           0.076363 -0.033737 -0.062997   
Reason_for_absence              -0.064245 -0.117925 -0.078608   
Month_of_absence                -0.000043  0.407770 -0.001520   
Day_of_the_week                  0.034468  0.046493  0.004459   
Transportation_expense          -0.224163  0.036995 -0.227542   
Distance_from_Residence_to_Work -0.486160 -0.063108 -0.145886   
Service_time                    -0.272704 -0.010904  0.670979   
Hit_target                       0.018789 -0.061154 -0.039224   
Disciplinary_failure             0.004502  0.151766  0.104304   
Social_drinker                  -0.451338 -0.045982  0.213183   
Social_smoker                   -0.010826 -0.048671  0.121738   
Body_mass_index                 -0.306924 -0.011031  0.470688   
Absenteeism_time_in_hours       -0.017997 -0.005615  0.065760   

                                 Work load Average/day   Education       Son  \
ID                                             0.092457  -0.036254  0.002767   
Seasons                                        0.150439  -0.002951  0.046950   
Age                                           -0.039425  -0.221882  0.056984   
Work load Average/day                          1.000000  -0.074960  0.027820   
Education                                     -0.074960   1.000000 -0.188622   
Son                                            0.027820  -0.188622  1.000000   
Pet                                            0.007114  -0.053554  0.108917   
Weight                                        -0.038522  -0.300574 -0.139552   
Height                                         0.103315   0.100977 -0.014208   
Reason_for_absence                            -0.123472  -0.047357 -0.055364   
Month_of_absence                              -0.169989  -0.066128  0.079031   
Day_of_the_week                                0.015646   0.058516  0.098079   
Transportation_expense                         0.005438  -0.055065  0.383001   
Distance_from_Residence_to_Work               -0.068677  -0.259605  0.054230   
Service_time                                  -0.000668  -0.213000 -0.047128   
Hit_target                                    -0.089445   0.101062 -0.014091   
Disciplinary_failure                           0.029026  -0.059298  0.072096   
Social_drinker                                -0.033713  -0.420013  0.206376   
Social_smoker                                  0.030968   0.032727  0.156088   
Body_mass_index                               -0.090709  -0.366884 -0.144150   
Absenteeism_time_in_hours                      0.024749  -0.046235  0.113756   

                                      Pet    Weight    Height  \
ID                              -0.041418 -0.254222  0.076363   
Seasons                          0.012356 -0.026278 -0.033737   
Age                             -0.231226  0.418730 -0.062997   
Work load Average/day            0.007114 -0.038522  0.103315   
Education                       -0.053554 -0.300574  0.100977   
Son                              0.108917 -0.139552 -0.014208   
Pet                              1.000000 -0.103770 -0.103143   
Weight                          -0.103770  1.000000  0.306802   
Height                          -0.103143  0.306802  1.000000   
Reason_for_absence              -0.055911 -0.000269 -0.079267   
Month_of_absence                 0.047787  0.023278 -0.068942   
Day_of_the_week                 -0.028885 -0.128980 -0.082133   
Tr

In [139]:
corelation['Absenteeism_time_in_hours'].sort_values()

Reason_for_absence                -0.173116
Day_of_the_week                   -0.124361
Disciplinary_failure              -0.124248
Distance_from_Residence_to_Work   -0.088363
Body_mass_index                   -0.049719
Education                         -0.046235
Pet                               -0.028277
ID                                -0.017997
Social_smoker                     -0.008936
Seasons                           -0.005615
Weight                             0.015789
Service_time                       0.019029
Month_of_absence                   0.024345
Work load Average/day              0.024749
Hit_target                         0.026695
Transportation_expense             0.027585
Social_drinker                     0.065067
Age                                0.065760
Son                                0.113756
Height                             0.144420
Absenteeism_time_in_hours          1.000000
Name: Absenteeism_time_in_hours, dtype: float64

In [140]:
f1='Reason_for_absence'
f2='Height'

In [141]:
basex=np.array(xtrain[[f1,f2]])
xtest=np.array(xtest[[f1,f2]])

In [142]:
centroids,classifications =fit(basex,k,max_iter,cent_change)

In [143]:
centroids

{0: array([0.96575342, 0.20963055]),
 1: array([0.41294643, 0.87878788]),
 2: array([0.86875   , 0.65757576]),
 3: array([0.77020677, 0.21590909]),
 4: array([0.30509582, 0.24815225])}

In [144]:
classifications

{0: [array([0.92857143, 0.27272727]),
  array([0.89285714, 0.27272727]),
  array([0.96428571, 0.24242424]),
  array([0.96428571, 0.27272727]),
  array([0.89285714, 0.21212121]),
  array([0.92857143, 0.27272727]),
  array([1.        , 0.24242424]),
  array([0.92857143, 0.18181818]),
  array([0.96428571, 0.21212121]),
  array([0.89285714, 0.21212121]),
  array([0.92857143, 0.21212121]),
  array([1.        , 0.21212121]),
  array([1.        , 0.15151515]),
  array([0.96428571, 0.21212121]),
  array([1.        , 0.15151515]),
  array([0.92857143, 0.12121212]),
  array([0.96428571, 0.21212121]),
  array([1.        , 0.15151515]),
  array([0.96428571, 0.27272727]),
  array([0.96428571, 0.21212121]),
  array([0.89285714, 0.27272727]),
  array([0.89285714, 0.18181818]),
  array([0.89285714, 0.18181818]),
  array([1.        , 0.21212121]),
  array([0.92857143, 0.12121212]),
  array([0.96428571, 0.24242424]),
  array([1.        , 0.18181818]),
  array([1.        , 0.21212121]),
  array([0.964285

In [151]:
for centroid in centroids:
    plt.scatter(centroids[centroid][0],centroids[centroid][1], marker='+',color='y',s=100)
    
for classification in classifications:
    color=colors[classification]
    
    for next_datapoint in classifications[classification]:
        plt.scatter(next_datapoint[0],next_datapoint[1],marker='.',color=color,s=50)
        
for test in xtest:
    classification=predict(test,centroids)
    plt.scatter(test[0],test[1],marker="*",color=colors[classification],s=100)