## Combined Cycle Power Plant

A combined cycle power plant (CCPP) is composed of gas turbines (GT), steam turbines (ST) and heat recovery steam generators. In a CCPP, the electricity is generated by gas and steam turbines, which are combined in one cycle, and is transferred from one turbine to another.The dataset contains 9568 data points collected from a Combined Cycle Power Plant over 6 years (2006-2011), when the power plant was set to work with full load.

We need to predict the net hourly electrical energy output(PE) of the power plant using the features of Temperature(AT), Ambient Pressure(AP), Relative Humidity(RH) and Exhaust Vacuum(V).

Combined Cycle Power Plant [dataset](https://archive.ics.uci.edu/ml/datasets/combined+cycle+power+plant)
    

In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

In [59]:
df=pd.read_excel("C:/Users/Venu/Desktop/HDS/Capstone Project 1/Folds5x2_pp.xlsx")

In [60]:
df

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
5     26.27  59.44  1012.23  58.77  443.67
6     15.89  43.96  1014.02  75.24  467.35
7      9.48  44.71  1019.12  66.43  478.42
8     14.64  45.00  1021.78  41.25  475.98
9     11.74  43.56  1015.14  70.72  477.50
10    17.99  43.72  1008.64  75.04  453.02
11    20.14  46.93  1014.66  64.22  453.99
12    24.34  73.50  1011.31  84.15  440.29
13    25.71  58.59  1012.77  61.83  451.28
14    26.19  69.34  1009.48  87.59  433.99
15    21.42  43.79  1015.76  43.08  462.19
16    18.21  45.00  1022.86  48.84  467.54
17    11.04  41.74  1022.60  77.51  477.20
18    14.45  52.75  1023.97  63.59  459.85
19    13.97  38.47  1015.15  55.28  464.30
20    17.76  42.42  1009.09  66.26  468.27
21     5.41  40.07  1019.16  64.77  495.24
22     7.76  42.28  1008.52  83.31  483.80
23    27.23  63.90  1014.30  47.19  443.61
24    27.36  48.60  1003.18  54.93  436.06
25    27.47  70.72  1009.97  74.62  443.25
26    14.60  39.31  1011.11  72.52  464.16
27     7.91  39.96  1023.57  88.44  475.52
28     5.81  35.79  1012.14  92.28  484.41
29    30.53  65.18  1012.69  41.85  437.89
...     ...    ...      ...    ...     ...
9538   8.64  38.56  1016.51  66.03  484.45
9539  10.53  37.50  1008.55  99.91  472.32
9540  23.53  50.05  1005.63  78.40  443.71
9541  24.90  67.25  1017.77  66.17  433.71
9542   5.01  39.40  1003.69  91.90  475.34
9543  22.66  69.84  1006.16  82.79  439.06
9544  29.76  57.19  1008.59  51.10  436.21
9545  26.30  61.41  1012.45  56.85  448.55
9546  30.17  74.22  1007.46  49.27  432.00
9547   8.02  40.23  1017.42  90.26  484.22
9548  19.12  50.16  1011.52  99.71  451.49
9549  14.87  42.18  1015.23  74.41  465.89
9550   9.71  42.44  1014.29  94.03  481.03
9551  24.33  77.54  1008.50  82.45  435.38
9552   7.17  39.40  1011.48  90.38  484.33
9553  24.61  62.96  1020.10  63.83  445.79
9554  23.48  66.44  1011.28  61.11  443.21
9555  23.70  70.32  1007.21  66.85  439.59
9556  25.44  69.59  1008.22  80.73  433.97
9557  17.46  62.10  1019.96  83.99  451.06
9558  22.97  62.40  1010.25  75.18  445.30
9559  26.22  49.82  1015.48  55.80  454.20
9560  23.27  68.28  1005.01  74.83  444.86
9561  11.76  41.58  1020.91  88.35  465.45
9562  14.02  40.10  1015.56  82.44  467.32
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

Using all features to implement the model

In [61]:
feature=pd.concat([df.AT,df.V,df.AP,df.RH],axis=1)

In [62]:
target=pd.concat([df.PE],axis=1)

In [63]:
data=np.array(df.iloc[:,:-1])
data

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [64]:
x1=df["AT"]
x2=df["V"]
x3=df["AP"]
x4=df["RH"]
y=df["PE"]

In [65]:
X=np.array(feature)
Y=np.array(y)

In [66]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [67]:
Y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [68]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

Ranging the X and Y values from -1 to 1

In [69]:
X=X.reshape(-1,1)
Y=Y.reshape(-1,1)

In [70]:
X=scaler.fit_transform(X)
Y=scaler.fit_transform(Y)

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
X_train,X_test,Y_train,Y_test=train_test_split(feature,Y,test_size=0.3)

In [73]:
from sklearn.linear_model import LinearRegression

In [74]:
regressor = LinearRegression()

In [75]:
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [77]:
Y_pred=regressor.predict(X_test)

In [78]:
Y_pred

array([[0.11424294],
       [0.75749178],
       [0.47841546],
       ...,
       [0.41142421],
       [0.75935473],
       [0.30515263]])

In [79]:
for i in zip(Y_pred,Y_test):
    print(i)

(array([0.11424294]), array([0.19536424]))
(array([0.75749178]), array([0.76927152]))
(array([0.47841546]), array([0.49536424]))
(array([0.40925436]), array([0.4205298]))
(array([0.59380808]), array([0.59324503]))
(array([0.50767767]), array([0.48357616]))
(array([0.32707491]), array([0.28410596]))
(array([0.67015329]), array([0.76927152]))
(array([0.28572046]), array([0.35682119]))
(array([0.66748088]), array([0.68953642]))
(array([0.21137431]), array([0.24039735]))
(array([0.40268789]), array([0.41986755]))
(array([0.31750762]), array([0.43470199]))
(array([0.17964155]), array([0.13536424]))
(array([0.37727937]), array([0.34039735]))
(array([0.85260567]), array([0.95178808]))
(array([0.41551301]), array([0.51668874]))
(array([0.78434861]), array([0.7813245]))
(array([0.35846485]), array([0.34688742]))
(array([0.6303585]), array([0.58741722]))
(array([0.19795588]), array([0.27125828]))
(array([0.5382825]), array([0.57403974]))
(array([0.27465842]), array([0.23721854]))
(array([0.83319

(array([0.26360268]), array([0.21245033]))
(array([0.73217319]), array([0.83086093]))
(array([0.23860108]), array([0.22794702]))
(array([0.65481867]), array([0.67311258]))
(array([0.24384843]), array([0.20397351]))
(array([0.24048368]), array([0.29682119]))
(array([0.68303195]), array([0.72066225]))
(array([0.37946289]), array([0.39456954]))
(array([0.11213221]), array([0.24]))
(array([0.43200235]), array([0.47456954]))
(array([0.49182109]), array([0.47443709]))
(array([0.13294986]), array([0.12543046]))
(array([0.17356869]), array([0.17629139]))
(array([0.21825909]), array([0.1407947]))
(array([0.26453086]), array([0.26754967]))
(array([0.19611121]), array([0.15880795]))
(array([0.20487457]), array([0.17231788]))
(array([0.3602413]), array([0.40569536]))
(array([0.48145175]), array([0.46953642]))
(array([0.2320638]), array([0.20596026]))
(array([0.68508122]), array([0.70198675]))
(array([0.31923202]), array([0.39602649]))
(array([0.2157778]), array([0.16198675]))
(array([0.43691382]),

(array([0.33199985]), array([0.30370861]))
(array([0.61227163]), array([0.6807947]))
(array([0.51844321]), array([0.53390728]))
(array([0.26739892]), array([0.32503311]))
(array([0.66173781]), array([0.73059603]))
(array([0.27820774]), array([0.20913907]))
(array([0.72195687]), array([0.9192053]))
(array([0.87939091]), array([0.91523179]))
(array([0.67837898]), array([0.54768212]))
(array([0.12760438]), array([0.22741722]))
(array([0.23082917]), array([0.22900662]))
(array([0.58345844]), array([0.56198675]))
(array([0.51722443]), array([0.48781457]))
(array([0.52926015]), array([0.61059603]))
(array([0.58552526]), array([0.64794702]))
(array([0.15311649]), array([0.21801325]))
(array([0.758135]), array([0.8418543]))
(array([0.83203049]), array([0.88635762]))
(array([0.30268467]), array([0.31801325]))
(array([0.80770965]), array([0.89337748]))
(array([0.47785849]), array([0.5]))
(array([0.31538211]), array([0.27655629]))
(array([0.12966457]), array([0.16582781]))
(array([0.33033589]), a

(array([0.75437208]), array([0.8392053]))
(array([0.30534629]), array([0.3194702]))
(array([0.78984612]), array([0.8592053]))
(array([0.69551684]), array([0.74556291]))
(array([0.82052122]), array([0.8415894]))
(array([0.55120814]), array([0.61708609]))
(array([0.24997787]), array([0.30384106]))
(array([0.45932829]), array([0.43245033]))
(array([0.80464577]), array([0.81615894]))
(array([0.35070207]), array([0.27139073]))
(array([0.65517501]), array([0.72688742]))
(array([0.6707882]), array([0.65496689]))
(array([0.2326961]), array([0.22635762]))
(array([0.80860746]), array([0.8018543]))
(array([0.19318393]), array([0.23205298]))
(array([0.41025264]), array([0.34556291]))
(array([0.31267054]), array([0.4413245]))
(array([0.65177119]), array([0.67377483]))
(array([0.15297703]), array([0.19059603]))
(array([0.20858698]), array([0.18516556]))
(array([0.79784774]), array([0.87337748]))
(array([0.18686851]), array([0.26529801]))
(array([0.33152902]), array([0.33205298]))
(array([0.19864103]

(array([0.68571534]), array([0.7418543]))
(array([0.6507347]), array([0.73112583]))
(array([0.62247333]), array([0.68622517]))
(array([0.32538021]), array([0.31231788]))
(array([0.83724096]), array([0.74423841]))
(array([0.60843125]), array([0.58291391]))
(array([0.54057628]), array([0.50119205]))
(array([0.57947247]), array([0.60940397]))
(array([0.64804789]), array([0.69099338]))
(array([0.15335224]), array([0.21933775]))
(array([0.41561699]), array([0.34807947]))
(array([0.64409334]), array([0.62490066]))
(array([0.41191657]), array([0.5007947]))
(array([0.39064735]), array([0.43735099]))
(array([0.38347038]), array([0.41629139]))
(array([0.56191525]), array([0.64384106]))
(array([0.63354436]), array([0.69470199]))
(array([0.38756764]), array([0.42940397]))
(array([0.70723846]), array([0.66887417]))
(array([0.66413539]), array([0.68304636]))
(array([0.17235018]), array([0.32821192]))
(array([0.26062337]), array([0.27655629]))
(array([0.51688928]), array([0.45470199]))
(array([0.8040

(array([0.17420181]), array([0.2984106]))
(array([0.64645525]), array([0.68754967]))
(array([0.19910648]), array([0.25311258]))
(array([0.18115828]), array([0.19576159]))
(array([0.84217254]), array([0.89986755]))
(array([0.17684307]), array([0.15509934]))
(array([0.32155015]), array([0.31986755]))
(array([0.41293605]), array([0.38092715]))
(array([0.46553451]), array([0.39576159]))
(array([0.22960911]), array([0.27139073]))
(array([0.35517013]), array([0.32834437]))
(array([0.78313977]), array([0.79748344]))
(array([0.79416203]), array([0.7797351]))
(array([0.60859096]), array([0.57456954]))
(array([0.27376805]), array([0.21960265]))
(array([0.19041261]), array([0.20370861]))
(array([0.82079206]), array([0.79099338]))
(array([0.58221809]), array([0.67523179]))
(array([0.79775921]), array([0.81430464]))
(array([0.70807239]), array([0.65417219]))
(array([0.08467313]), array([0.17324503]))
(array([0.18629786]), array([0.32119205]))
(array([0.52248613]), array([0.53218543]))
(array([0.749

(array([0.48073936]), array([0.43629139]))
(array([0.10900089]), array([0.13205298]))
(array([0.23628678]), array([0.16927152]))
(array([0.57263405]), array([0.52609272]))
(array([0.39339848]), array([0.33059603]))
(array([0.71554609]), array([0.71788079]))
(array([0.41966902]), array([0.39337748]))
(array([0.72894127]), array([0.73086093]))
(array([0.33539425]), array([0.30794702]))
(array([0.3415657]), array([0.36887417]))
(array([0.1208788]), array([0.19536424]))
(array([0.30761499]), array([0.30701987]))
(array([0.62616185]), array([0.70596026]))
(array([0.28690227]), array([0.29072848]))
(array([0.43642077]), array([0.37483444]))
(array([0.8426137]), array([0.89721854]))
(array([0.23004518]), array([0.21655629]))
(array([0.77738265]), array([0.78596026]))
(array([0.14415213]), array([0.11933775]))
(array([0.16071407]), array([0.24887417]))
(array([0.69614267]), array([0.75960265]))
(array([0.07761878]), array([0.1784106]))
(array([0.55097075]), array([0.60490066]))
(array([0.13956

In [80]:
from sklearn.metrics import mean_squared_error, r2_score

In [85]:
np.sqrt(mean_squared_error(Y_test,Y_pred))

0.06045821261531814

In [84]:
r2_score(Y_test,Y_pred)

0.9278735474807325